<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.2.4" />
    <PackageReference Include="QuestPDF" Version="2023.5.2" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AGP.Gordon.CommonLayer\AGP.Gordon.CommonLayer.csproj" />
    <ProjectReference Include="..\AGP.Gordon.DataLayer\AGP.Gordon.DataAccessLayer.csproj" />
  </ItemGroup>

</Project>
